// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @param {models$0.Card[]} cards
 * @returns {$CancellablePromise<{ [_: string]: models$0.Seller }>}
 */
export function FindOptimalSellers(cards) {
    return $Call.ByID(3544759894, cards).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Seller.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
