// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CardQuery describes the set of parameters that can be used when requesting
 * data from an external cards marketplace. CardName is mandatory while the
 * remaining fields are optional filters that will be applied by specific
 * platform implementations when supported.
 */
export class CardQuery {
    /**
     * Creates a new CardQuery instance.
     * @param {Partial<CardQuery>} [$$source = {}] - The source object to create the CardQuery.
     */
    constructor($$source = {}) {
        if (!("Card" in $$source)) {
            /**
             * @member
             * @type {models$0.Card}
             */
            this["Card"] = (new models$0.Card());
        }
        if (!("Language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Language"] = "";
        }
        if (!("ShipmentDestination" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ShipmentDestination"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CardQuery instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CardQuery}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Card" in $$parsedSource) {
            $$parsedSource["Card"] = $$createField0_0($$parsedSource["Card"]);
        }
        return new CardQuery(/** @type {Partial<CardQuery>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = models$0.Card.createFrom;
