// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Card {
    /**
     * Creates a new Card instance.
     * @param {Partial<Card>} [$$source = {}] - The source object to create the Card.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("Quantity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Quantity"] = 0;
        }
        if (!("CardName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CardName"] = "";
        }
        if (!("EditionName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EditionName"] = "";
        }
        if (!("Link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Link"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Card instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Card}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Card(/** @type {Partial<Card>} */($$parsedSource));
    }
}

export class Seller {
    /**
     * Creates a new Seller instance.
     * @param {Partial<Seller>} [$$source = {}] - The source object to create the Seller.
     */
    constructor($$source = {}) {
        if (!("SellerName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SellerName"] = "";
        }
        if (!("SellerCountry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SellerCountry"] = "";
        }
        if (!("CardCondition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CardCondition"] = "";
        }
        if (!("CardsAmmount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["CardsAmmount"] = 0;
        }
        if (!("Price" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Price"] = 0;
        }
        if (!("Currency" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Currency"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Seller instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Seller}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Seller(/** @type {Partial<Seller>} */($$parsedSource));
    }
}
