// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cardsplatform$0 from "../models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} key
 * @returns {$CancellablePromise<[models$0.Seller[], boolean]>}
 */
export function GetCachedSellers(key) {
    return $Call.ByID(262804232, key).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }));
}

/**
 * @param {cardsplatform$0.CardQuery} query
 * @returns {$CancellablePromise<models$0.Seller[]>}
 */
export function GetCardSellers(query) {
    return $Call.ByID(596670228, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string[]} cardIDs
 * @returns {$CancellablePromise<$models.SellerFetchStatus[]>}
 */
export function GetFetchStatuses(cardIDs) {
    return $Call.ByID(3481720704, cardIDs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ParseSellerListings processes the HTML body of a Cardmarket page and extracts all seller rows.
 * @param {string} body
 * @returns {$CancellablePromise<models$0.Seller[]>}
 */
export function ParseSellerListings(body) {
    return $Call.ByID(2730040335, body).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Test() {
    return $Call.ByID(3820613482);
}

// Private type creation functions
const $$createType0 = models$0.Seller.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SellerFetchStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
