// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SellerFetchStatus {
    /**
     * Creates a new SellerFetchStatus instance.
     * @param {Partial<SellerFetchStatus>} [$$source = {}] - The source object to create the SellerFetchStatus.
     */
    constructor($$source = {}) {
        if (!("cardId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cardId"] = "";
        }
        if (!("hadError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hadError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = undefined;
        }
        if (!("sellersFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sellersFound"] = false;
        }
        if (!("fetchAttempted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fetchAttempted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SellerFetchStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SellerFetchStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SellerFetchStatus(/** @type {Partial<SellerFetchStatus>} */($$parsedSource));
    }
}
